version: "2"
services:
  postgres:
    image: postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=iclasspg
    ports:
      - '5432:5432'

  iclassbe:
    build:
      context: .
    environment:
      - DB_PASSWORD=iclasspg
      - DB_SCHEMA=postgres
      - DB_USER=postgres
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_SSL=false
    depends_on:
      - postgres
    ports:
      - '8000:8000'
